### PR TITLE
Feature/802.15.4 2015

### PR DESCRIPTION
**Pull request by korken89**
Updating the existing PR

### CODE REVIEW

**Comment by korken89** [comment]
Hi, I continued the existing PR https://github.com/braun-embedded/rust-ieee802.15.4/pull/40

**Comment by korken89** [comment]
It would be much appreciated if this could be released as well :)

**Comment by hannobraun** [comment]
Thanks for picking this up, @korken89! I don't have the bandwidth to review it right this moment, but I'll do so soon. Most likely next week. I'll publish a new release right after.

**Comment by korken89** [comment]
Thanks!

**Comment by hannobraun** [comment]
Since I last posted here, [things happened](https://github.com/rust-iot/rust-ieee802.15.4/issues/45), and this repository has been transferred to Rust IoT. I no longer have the power to merge this PR, or make a release (well, technically I can still make a release, but I think it would be in bad taste :grin:).

I hope that the new management will take care of this pull request shortly.

cc @ryankurte, @henrikssn 
(I tried to ping @rust-iot/core, which doesn't seem to work; maybe because it has no public members?)

**Review by ryankurte — APPROVED** [review]
lgtm, any opinions @henrikssn?

**Comment by henrikssn** [comment]
LGTM

**Comment by henrikssn** [comment]
Published as ~~`v0.5.1`~~ `v0.6.0`

**Comment by ryankurte** [comment]
nice work, thanks folks!

**Pull request merged**
